import { gridFromStrings, type GameMap } from '../../engine/map';

/** Shared arena shell */
function arena(
  id: string,
  name: string,
  episode: number,
  nextMapId: string | null,
  floor: string,
  ceil: string,
  extras: GameMap['entities'],
  bossVariant: string,
): GameMap {
  return {
    id,
    name,
    episode,
    nextMapId,
    width: 18,
    height: 16,
    grid: gridFromStrings([
      '111111111111111111',
      '1................1',
      '1..8..........8..1',
      '1................1',
      '1......1111......1',
      '1......1..1......1',
      '1................1',
      '1................1',
      '1................1',
      '1................1',
      '1......1..1......1',
      '1......1111......1',
      '1................1',
      '1..8..........8..1',
      '1................1',
      '111111111111111111',
    ]).grid,
    floorColor: floor,
    ceilingColor: ceil,
    spawn: { x: 9, y: 13.5, angle: -Math.PI / 2 },
    entities: [
      ...extras,
      { type: 'boss', variant: bossVariant, x: 9, y: 3.5 },
      { type: 'pickup', x: 2.5, y: 13.5, kind: 'resolve' },
      { type: 'pickup', x: 15.5, y: 13.5, kind: 'voice' },
      { type: 'exit', x: 9, y: 14.2 },
    ],
  };
}

function corridorMap(
  id: string,
  name: string,
  episode: number,
  nextMapId: string,
  floor: string,
  ceil: string,
  wallDigit: number,
  entities: GameMap['entities'],
): GameMap {
  const w = String(wallDigit);
  const layout = gridFromStrings([
    '1111111111111111111111',
    '1....................1',
    `1..${w}....1......${w}.....1`,
    '1.......1............1',
    '1..111111......1111..1',
    '1..1..............1..1',
    `1..1...2....2.....1..1`,
    '1..1..............1..1',
    '1..1111..33..111111..1',
    '1.......3..3.........1',
    '1.......3..3....5....1',
    `1..4...........4.....1`,
    '1....................1',
    '111111119..91111111111',
    '1....................1',
    `1...${w}...........${w}....1`,
    '1....................1',
    '1....................1',
    '1....................1',
    '1111111111111111111111',
  ]);
  return {
    id,
    name,
    episode,
    nextMapId,
    width: layout.width,
    height: layout.height,
    grid: layout.grid,
    floorColor: floor,
    ceilingColor: ceil,
    spawn: { x: 2.5, y: 2.5, angle: Math.PI / 2 },
    entities,
  };
}

// ——— Episode 2: Campus ———
export const ep2Quad: GameMap = corridorMap(
  'ep2_quad',
  'Quad of Eternal Protest',
  2,
  'ep2_admin',
  '#3d4a3a',
  '#6a8a60',
  8,
  [
    {
      type: 'plaque',
      x: 4.5,
      y: 3.5,
      id: 'P05',
      title: 'Syllabus of Spin',
      text: '“Required reading: feelings. Elective: facts.”',
    },
    {
      type: 'plaque',
      x: 16.5,
      y: 6.5,
      id: 'P06',
      title: 'Safe Space Sign',
      text: '“Safety is good. Cowardice is not a major.”',
    },
    {
      type: 'button',
      x: 10.5,
      y: 12.5,
      flag: 'ep2_quad_gate',
      label: 'Admin Gate',
      openCells: [
        { x: 8, y: 13 },
        { x: 11, y: 13 },
      ],
    },
    { type: 'libtard', x: 8.5, y: 5.5 },
    { type: 'libtard', x: 14.5, y: 8.5 },
    { type: 'woke', x: 6.5, y: 10.5 },
    { type: 'woke', x: 12.5, y: 15.5 },
    { type: 'karen', x: 18.5, y: 4.5 },
    { type: 'pickup', x: 18.5, y: 2.5, kind: 'resolve' },
    { type: 'pickup', x: 3.5, y: 11.5, kind: 'voice' },
    { type: 'pickup', x: 10.5, y: 5.5, kind: 'key_red' },
    { type: 'pickup', x: 19.5, y: 16.5, kind: 'brand' },
    {
      type: 'secret_trigger',
      x: 17.5,
      y: 10.5,
      wallX: 18,
      wallY: 10,
      flag: 'ep2_s1',
    },
    {
      type: 'secret_trigger',
      x: 5.5,
      y: 6.5,
      wallX: 3,
      wallY: 4,
      flag: 'ep2_s2',
    },
    { type: 'pickup', x: 4.5, y: 5.5, kind: 'brand' },
    { type: 'exit', x: 10.5, y: 17.5 },
  ],
);

export const ep2Admin: GameMap = corridorMap(
  'ep2_admin',
  'Administration Labyrinth',
  2,
  'ep2_hydra',
  '#3a3a48',
  '#2a3040',
  5,
  [
    {
      type: 'plaque',
      x: 6.5,
      y: 6.5,
      id: 'P07',
      title: 'Hydra Tweet',
      text: '“They blocked me. I built a bigger platform.”',
    },
    {
      type: 'phone',
      x: 16.5,
      y: 10.5,
      flag: 'ep2_phone',
      label: 'Dean Hotline',
      effect: 'open',
      openCells: [
        { x: 8, y: 13 },
        { x: 11, y: 13 },
      ],
      message: 'Dean distracted — side gate open!',
    },
    { type: 'libtard', x: 9.5, y: 4.5 },
    { type: 'libtard', x: 14.5, y: 7.5 },
    { type: 'woke', x: 5.5, y: 9.5 },
    { type: 'woke', x: 11.5, y: 12.5 },
    { type: 'woke', x: 17.5, y: 15.5 },
    { type: 'karen', elite: true, x: 8.5, y: 15.5 },
    { type: 'pickup', x: 18.5, y: 2.5, kind: 'resolve' },
    { type: 'pickup', x: 2.5, y: 6.5, kind: 'voice' },
    { type: 'pickup', x: 10.5, y: 5.5, kind: 'key_red' },
    { type: 'pickup', x: 19.5, y: 11.5, kind: 'brand' },
    {
      type: 'secret_trigger',
      x: 15.5,
      y: 10.5,
      wallX: 16,
      wallY: 10,
      flag: 'ep2_admin_sec',
    },
    {
      type: 'secret_trigger',
      x: 3.5,
      y: 11.5,
      wallX: 3,
      wallY: 11,
      flag: 'ep2_admin_sec2',
    },
    { type: 'pickup', x: 4.5, y: 12.5, kind: 'brand' },
    { type: 'exit', x: 10.5, y: 17.5 },
  ],
);

export const ep2Hydra = arena(
  'ep2_hydra',
  'Cancel Culture Hydra',
  2,
  'ep3_forms',
  '#2a2030',
  '#1a1020',
  [
    {
      type: 'plaque',
      x: 3.5,
      y: 2.5,
      id: 'P07b',
      title: 'Blocked Banner',
      text: '“Chop one head. Two hashtags grow.”',
    },
    {
      type: 'phone',
      x: 9,
      y: 5.5,
      flag: 'hydra_silence',
      label: 'Report Account',
      effect: 'silence',
      message: 'Hydra feed throttled — fewer heads for now!',
    },
    {
      type: 'secret_trigger',
      x: 14.5,
      y: 12.5,
      wallX: 15,
      wallY: 13,
      flag: 'ep2_boss_sec',
    },
    { type: 'pickup', x: 14.5, y: 12.5, kind: 'brand' },
  ],
  'hydra',
);

// ——— Episode 3: Bureau ———
export const ep3Forms: GameMap = corridorMap(
  'ep3_forms',
  'Bureau of Infinite Forms',
  3,
  'ep3_autopen',
  '#4a4840',
  '#3a3830',
  4,
  [
    {
      type: 'plaque',
      x: 4.5,
      y: 3.5,
      id: 'P08',
      title: 'Form 27B/6',
      text: '“If a form cannot be finished, neither can freedom.”',
    },
    {
      type: 'plaque',
      x: 16.5,
      y: 15.5,
      id: 'P10',
      title: 'Escalator Dream',
      text: '“Going up is a choice. Going down is a policy.”',
    },
    {
      type: 'button',
      x: 10.5,
      y: 12.5,
      flag: 'ep3_gate',
      label: 'Stamp Approval',
      openCells: [
        { x: 8, y: 13 },
        { x: 11, y: 13 },
      ],
    },
    { type: 'bureaucrat', x: 7.5, y: 5.5 },
    { type: 'bureaucrat', x: 13.5, y: 8.5 },
    { type: 'bureaucrat', x: 10.5, y: 11.5 },
    { type: 'libtard', x: 5.5, y: 14.5 },
    { type: 'karen', x: 17.5, y: 6.5 },
    { type: 'pickup', x: 18.5, y: 2.5, kind: 'resolve' },
    { type: 'pickup', x: 2.5, y: 11.5, kind: 'voice' },
    { type: 'pickup', x: 10.5, y: 5.5, kind: 'key_red' },
    { type: 'pickup', x: 19.5, y: 16.5, kind: 'brand' },
    {
      type: 'secret_trigger',
      x: 17.5,
      y: 10.5,
      wallX: 18,
      wallY: 10,
      flag: 'ep3_s1',
    },
    {
      type: 'secret_trigger',
      x: 5.5,
      y: 6.5,
      wallX: 3,
      wallY: 4,
      flag: 'ep3_s2',
    },
    { type: 'pickup', x: 4.5, y: 5.5, kind: 'brand' },
    { type: 'exit', x: 10.5, y: 17.5 },
  ],
);

export const ep3Autopen = arena(
  'ep3_autopen',
  'Autopen Chamber',
  3,
  'ep4_warehouse',
  '#3a3530',
  '#201810',
  [
    {
      type: 'plaque',
      x: 3.5,
      y: 2.5,
      id: 'P09',
      title: 'Autopen Manual',
      text: '“A signature without a soul is just ink.”',
    },
    {
      type: 'phone',
      x: 9,
      y: 5.5,
      flag: 'autopen_silence',
      label: 'Ink Reservoir Control',
      effect: 'silence',
      message: 'Ink flow interrupted — Autopen slowed!',
    },
    {
      type: 'secret_trigger',
      x: 3.5,
      y: 12.5,
      wallX: 2,
      wallY: 13,
      flag: 'ep3_boss_sec',
    },
    { type: 'pickup', x: 3.5, y: 12.5, kind: 'brand' },
  ],
  'autopen',
);

// ——— Episode 4: Ballots ———
export const ep4Warehouse: GameMap = corridorMap(
  'ep4_warehouse',
  'Ballot Warehouse',
  4,
  'ep4_fraud',
  '#2a2a35',
  '#151520',
  1,
  [
    {
      type: 'plaque',
      x: 4.5,
      y: 3.5,
      id: 'P11',
      title: 'Ballot Dust',
      text: '“Count twice. Trust once. Verify always.”',
    },
    {
      type: 'plaque',
      x: 16.5,
      y: 15.5,
      id: 'P12',
      title: 'Warehouse Echo',
      text: '“The boxes whispered ‘later.’ I said ‘now.’”',
    },
    {
      type: 'button',
      x: 10.5,
      y: 12.5,
      flag: 'ep4_gate',
      label: 'Bay Door',
      openCells: [
        { x: 8, y: 13 },
        { x: 11, y: 13 },
      ],
    },
    { type: 'bureaucrat', x: 8.5, y: 5.5 },
    { type: 'bureaucrat', x: 14.5, y: 8.5 },
    { type: 'woke', x: 6.5, y: 11.5 },
    { type: 'libtard', x: 12.5, y: 14.5 },
    { type: 'karen', elite: true, x: 17.5, y: 7.5 },
    { type: 'pickup', x: 18.5, y: 2.5, kind: 'resolve' },
    { type: 'pickup', x: 2.5, y: 11.5, kind: 'voice' },
    { type: 'pickup', x: 10.5, y: 5.5, kind: 'key_red' },
    { type: 'pickup', x: 19.5, y: 16.5, kind: 'brand' },
    {
      type: 'secret_trigger',
      x: 17.5,
      y: 10.5,
      wallX: 18,
      wallY: 10,
      flag: 'ep4_s1',
    },
    {
      type: 'secret_trigger',
      x: 5.5,
      y: 6.5,
      wallX: 3,
      wallY: 4,
      flag: 'ep4_s2',
    },
    {
      type: 'secret_trigger',
      x: 11.5,
      y: 15.5,
      wallX: 12,
      wallY: 16,
      flag: 'ep4_s3',
    },
    { type: 'pickup', x: 4.5, y: 5.5, kind: 'brand' },
    { type: 'exit', x: 10.5, y: 17.5 },
  ],
);

export const ep4Fraud = arena(
  'ep4_fraud',
  'Election Fraud',
  4,
  'ep5_court',
  '#1a1a28',
  '#100818',
  [
    {
      type: 'plaque',
      x: 3.5,
      y: 2.5,
      id: 'P13',
      title: 'Mirror of Polls',
      text: '“Polls measure fear. Rallies measure fire.”',
    },
    {
      type: 'phone',
      x: 9,
      y: 5.5,
      flag: 'fraud_silence',
      label: 'Audit Terminal',
      effect: 'silence',
      message: 'Audit running — maze freezes briefly!',
    },
    {
      type: 'secret_trigger',
      x: 14.5,
      y: 8.5,
      wallX: 15,
      wallY: 8,
      flag: 'ep4_boss_sec',
    },
    { type: 'pickup', x: 14.5, y: 8.5, kind: 'brand' },
  ],
  'fraud',
);

// ——— Episode 5: Tribunal ———
export const ep5Court: GameMap = corridorMap(
  'ep5_court',
  'Halls of Injunction',
  5,
  'ep5_tribunal',
  '#3a3a45',
  '#202030',
  2,
  [
    {
      type: 'plaque',
      x: 4.5,
      y: 3.5,
      id: 'P14',
      title: 'Gavel Crack',
      text: '“Justice delayed is a boss fight prolonged.”',
    },
    {
      type: 'plaque',
      x: 16.5,
      y: 15.5,
      id: 'P15',
      title: 'Injunction Etched',
      text: '“They paused my weapons. I raised my voice.”',
    },
    {
      type: 'button',
      x: 10.5,
      y: 12.5,
      flag: 'ep5_gate',
      label: 'Clerk Window',
      openCells: [
        { x: 8, y: 13 },
        { x: 11, y: 13 },
      ],
    },
    { type: 'bureaucrat', x: 8.5, y: 5.5 },
    { type: 'bureaucrat', x: 14.5, y: 8.5 },
    { type: 'libtard', x: 6.5, y: 11.5 },
    { type: 'libtard', x: 12.5, y: 14.5 },
    { type: 'woke', x: 17.5, y: 7.5 },
    { type: 'karen', elite: true, x: 9.5, y: 16.5 },
    { type: 'pickup', x: 18.5, y: 2.5, kind: 'resolve' },
    { type: 'pickup', x: 2.5, y: 11.5, kind: 'voice' },
    { type: 'pickup', x: 10.5, y: 5.5, kind: 'key_red' },
    { type: 'pickup', x: 19.5, y: 16.5, kind: 'brand' },
    {
      type: 'secret_trigger',
      x: 17.5,
      y: 10.5,
      wallX: 18,
      wallY: 10,
      flag: 'ep5_s1',
    },
    {
      type: 'secret_trigger',
      x: 5.5,
      y: 6.5,
      wallX: 3,
      wallY: 4,
      flag: 'ep5_s2',
    },
    { type: 'pickup', x: 4.5, y: 5.5, kind: 'brand' },
    { type: 'exit', x: 10.5, y: 17.5 },
  ],
);

export const ep5Tribunal = arena(
  'ep5_tribunal',
  'Rogue Judge Tribunal',
  5,
  'ep6_studio',
  '#2a2535',
  '#15101a',
  [
    {
      type: 'plaque',
      x: 3.5,
      y: 2.5,
      id: 'P16',
      title: 'Tribunal Mosaic',
      text: '“Three robes. Zero mandate. One problem.”',
    },
    {
      type: 'phone',
      x: 9,
      y: 5.5,
      flag: 'judge_silence',
      label: 'Appeal Hotline',
      effect: 'silence',
      message: 'Appeal filed — injunctions paused!',
    },
    {
      type: 'secret_trigger',
      x: 14.5,
      y: 12.5,
      wallX: 15,
      wallY: 13,
      flag: 'ep5_boss_sec',
    },
    { type: 'pickup', x: 14.5, y: 12.5, kind: 'brand' },
  ],
  'tribunal',
);

// ——— Episode 6: Media ———
export const ep6Studio: GameMap = corridorMap(
  'ep6_studio',
  'Prime Time Control Room',
  6,
  'ep6_leviathan',
  '#2a2030',
  '#401020',
  3,
  [
    {
      type: 'plaque',
      x: 4.5,
      y: 3.5,
      id: 'P17',
      title: 'Teleprompter Tears',
      text: '“The script ended. I did not.”',
    },
    {
      type: 'plaque',
      x: 16.5,
      y: 15.5,
      id: 'P18',
      title: 'Ratings Altar',
      text: '“If it bleeds, it leads. If it leads, I win the argument.”',
    },
    {
      type: 'button',
      x: 10.5,
      y: 12.5,
      flag: 'ep6_gate',
      label: 'On-Air Switch',
      openCells: [
        { x: 8, y: 13 },
        { x: 11, y: 13 },
      ],
    },
    { type: 'libtard', x: 8.5, y: 5.5 },
    { type: 'libtard', x: 14.5, y: 8.5 },
    { type: 'woke', x: 6.5, y: 11.5 },
    { type: 'woke', x: 12.5, y: 14.5 },
    { type: 'bureaucrat', x: 17.5, y: 7.5 },
    { type: 'karen', elite: true, x: 9.5, y: 16.5 },
    { type: 'pickup', x: 18.5, y: 2.5, kind: 'resolve' },
    { type: 'pickup', x: 2.5, y: 11.5, kind: 'voice' },
    { type: 'pickup', x: 10.5, y: 5.5, kind: 'key_red' },
    { type: 'pickup', x: 19.5, y: 16.5, kind: 'brand' },
    {
      type: 'secret_trigger',
      x: 17.5,
      y: 10.5,
      wallX: 18,
      wallY: 10,
      flag: 'ep6_s1',
    },
    {
      type: 'secret_trigger',
      x: 5.5,
      y: 6.5,
      wallX: 3,
      wallY: 4,
      flag: 'ep6_s2',
    },
    {
      type: 'secret_trigger',
      x: 11.5,
      y: 3.5,
      wallX: 9,
      wallY: 4,
      flag: 'ep6_s3',
    },
    { type: 'pickup', x: 4.5, y: 5.5, kind: 'brand' },
    { type: 'exit', x: 10.5, y: 17.5 },
  ],
);

export const ep6Leviathan = arena(
  'ep6_leviathan',
  'Media Leviathan',
  6,
  'ep7_approach', // special: game redirects via branch
  '#201018',
  '#100810',
  [
    {
      type: 'plaque',
      x: 3.5,
      y: 2.5,
      id: 'P18b',
      title: 'Chyron Throne',
      text: '“Change the channel. Change the weak point.”',
    },
    {
      type: 'phone',
      x: 9,
      y: 5.5,
      flag: 'media_silence',
      label: 'Remote Control',
      effect: 'silence',
      message: 'Channel flipped — Leviathan reels!',
    },
    {
      type: 'secret_trigger',
      x: 14.5,
      y: 12.5,
      wallX: 15,
      wallY: 13,
      flag: 'ep6_boss_sec',
    },
    { type: 'pickup', x: 14.5, y: 12.5, kind: 'brand' },
  ],
  'media',
);

// ——— Episode 7: Branch approaches + Oval ———
function approachMap(
  id: string,
  name: string,
  flavor: string,
  entitiesExtra: GameMap['entities'],
): GameMap {
  const layout = gridFromStrings([
    '11111111111111111111',
    '1..................1',
    '1..2....1....2.....1',
    '1.......1..........1',
    '1..111111....1111..1',
    '1..1............1..1',
    '1..1...8....8...1..1',
    '1..1............1..1',
    '1..1111......1111..1',
    '1..................1',
    '1........7.........1',
    '1..................1',
    '11111111111111111111',
  ]);
  return {
    id,
    name,
    episode: 7,
    nextMapId: 'ep7_oval',
    width: layout.width,
    height: layout.height,
    grid: layout.grid,
    floorColor: '#2a3040',
    ceilingColor: '#0a1f44',
    spawn: { x: 2.5, y: 2.5, angle: Math.PI / 2 },
    entities: [
      {
        type: 'plaque',
        x: 4.5,
        y: 2.5,
        id: flavor,
        title: name,
        text:
          id === 'ep7_gold'
            ? '“Brand paved this gold road. Walk it.”'
            : id === 'ep7_codex'
              ? '“The plaques led you here. Knowledge is a keycard.”'
              : '“The swamp fog is thick. Drain it.”',
      },
      { type: 'woke', x: 8.5, y: 5.5 },
      { type: 'libtard', x: 12.5, y: 6.5 },
      { type: 'bureaucrat', x: 10.5, y: 8.5 },
      { type: 'karen', elite: true, x: 6.5, y: 9.5 },
      { type: 'pickup', x: 16.5, y: 2.5, kind: 'resolve' },
      { type: 'pickup', x: 3.5, y: 9.5, kind: 'voice' },
      { type: 'pickup', x: 15.5, y: 9.5, kind: 'brand' },
      ...entitiesExtra,
      { type: 'exit', x: 10.5, y: 10.5 },
    ],
  };
}

export const ep7Gold = approachMap('ep7_gold', 'Golden Escalator Path', 'P19g', [
  {
    type: 'secret_trigger',
    x: 15.5,
    y: 5.5,
    wallX: 16,
    wallY: 4,
    flag: 'ep7g_s1',
  },
  {
    type: 'secret_trigger',
    x: 5.5,
    y: 6.5,
    wallX: 3,
    wallY: 4,
    flag: 'ep7g_s2',
  },
  { type: 'pickup', x: 4.5, y: 5.5, kind: 'brand' },
]);

export const ep7Codex = approachMap('ep7_codex', 'Codex Hall Path', 'P19c', [
  {
    type: 'plaque',
    x: 14.5,
    y: 3.5,
    id: 'P22',
    title: 'True Ending Key',
    text: '“The people were the final plaque all along.”',
  },
  {
    type: 'secret_trigger',
    x: 15.5,
    y: 5.5,
    wallX: 16,
    wallY: 4,
    flag: 'ep7c_s1',
  },
  {
    type: 'secret_trigger',
    x: 5.5,
    y: 6.5,
    wallX: 3,
    wallY: 4,
    flag: 'ep7c_s2',
  },
]);

export const ep7Swamp = approachMap('ep7_swamp', 'Swamp Approach', 'P19', [
  {
    type: 'plaque',
    x: 14.5,
    y: 3.5,
    id: 'P19',
    title: 'Swamp Fog',
    text: '“Drain it. Don’t sip it.”',
  },
  {
    type: 'secret_trigger',
    x: 15.5,
    y: 5.5,
    wallX: 16,
    wallY: 4,
    flag: 'ep7s_s1',
  },
  {
    type: 'secret_trigger',
    x: 5.5,
    y: 6.5,
    wallX: 3,
    wallY: 4,
    flag: 'ep7s_s2',
  },
]);

export const ep7Oval: GameMap = {
  id: 'ep7_oval',
  name: 'The Oval — Final Gauntlet',
  episode: 7,
  nextMapId: null,
  width: 18,
  height: 16,
  grid: gridFromStrings([
    '111111111111111111',
    '1................1',
    '1..2..........2..1',
    '1................1',
    '1......1111......1',
    '1......1..1......1',
    '1................1',
    '1................1',
    '1................1',
    '1................1',
    '1......1..1......1',
    '1......1111......1',
    '1................1',
    '1..2..........2..1',
    '1................1',
    '111111111111111111',
  ]).grid,
  floorColor: '#1a3040',
  ceilingColor: '#0a1f44',
  spawn: { x: 9, y: 13.5, angle: -Math.PI / 2 },
  entities: [
    {
      type: 'plaque',
      x: 3.5,
      y: 2.5,
      id: 'P20',
      title: 'Oval Threshold',
      text: '“The desk is Resolute. So am I.”',
    },
    {
      type: 'plaque',
      x: 14.5,
      y: 2.5,
      id: 'P21',
      title: 'Deepfake Warning',
      text: '“If it looks like me and lies, aim everything.”',
    },
    {
      type: 'phone',
      x: 9,
      y: 5.5,
      flag: 'swamp_silence',
      label: 'Drain Switch',
      effect: 'silence',
      message: 'Swamp pumps engaged — adds delayed!',
    },
    { type: 'boss', variant: 'swamp', x: 9, y: 3.5 },
    // secret deepfake mini-boss after swamp? spawn as second boss area - optional enemy
    { type: 'boss', variant: 'deepfake', x: 4.5, y: 8.5 },
    { type: 'pickup', x: 2.5, y: 13.5, kind: 'resolve' },
    { type: 'pickup', x: 15.5, y: 13.5, kind: 'voice' },
    { type: 'pickup', x: 9, y: 11.5, kind: 'brand' },
    {
      type: 'secret_trigger',
      x: 14.5,
      y: 12.5,
      wallX: 15,
      wallY: 13,
      flag: 'ep7_oval_sec',
    },
    { type: 'exit', x: 9, y: 14.2 },
  ],
};

/** Sentinel id — game rewrites next after leviathan */
export const EP7_APPROACH_SENTINEL = 'ep7_approach';
